name: Bridgecrew Scan

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Bridgecrew Scan
      id: bridgecrew
      uses: bridgecrewio/checkov-action@master
      with:
        api-key: ${{ secrets.BC_API_KEY }}
        directory: terraform/
        #soft_fail: true

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      if: success() || failure()
      with:
        sarif_file: results.sarif
