name: build
on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  update-bridgecrew:
    runs-on: [self-hosted, public, linux, x64]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Bridgecrew 
        id: Bridgecrew
        uses: bridgecrewio/bridgecrew-action@master 
        with:
          api-key: ${{ secrets.BC_API_KEY }}
