name: build
on:
  pull_request
jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: bridgecrewio/bridgecrew-action@master
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        with: 
          directory: "."
