name: build
on:
  push:
    branches:
      - master
      
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
        with:
          fetch-depth: 0
          token: ${{ env.GH_TOKEN }}
      - name: Run yor action
        uses: bridgecrewio/yor-action@main
