

name: Main
on: [push]
env:
  SPECTRAL_DSN: https://spk-cb09179194314e6bbc8e9e9e61b012bf@bruce-mountain-16192.herokuapp.com

jobs:
  build:
    name: Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: curl -L "https://bruce-mountain-16192.herokuapp.com/latest/x/sh?dsn=$SPECTRAL_DSN" | sh
      - name: Scan
        run: $HOME/.spectral/spectral --include-tags base,iac scan
