name: Prisma Cloud IaC Scan
on:
      pull_request:
            types:
                  - closed
#       push:
#             branches:
#                   - master
jobs:
      if_merged:
            if: github.event.pull_request.merged == true
            runs-on: ubuntu-latest
            steps:
                  - run: |
                        echo The PR was merged
      scan:
            runs-on: ubuntu-latest
            strategy:
                  matrix:
                        python-version: [3.8]
            steps:
            - name: Checkout repo
              uses: actions/checkout@v2
            - name: Run Bridgecrew 
              id: Bridgecrew
              uses: bridgecrewio/bridgecrew-action@master 
              env:
                PRISMA_API_URL: https://api4.prismacloud.io
              with:
                api-key: ${{ secrets.BC_API_KEY }}
                directory: terraform/
#                 soft_fail: true
