on:
  pull_request: {}
  push:
    branches:
    - main
    - master
name: OWASP dependency-check Action
jobs:
  owasp-dependency-check:
    name: OWASP dependency-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependency-check
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install dependency-check

      - name: run scan
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          dependency-check --project "demo-project-terraform" --scan "demo-project-terraform"
