name: tfsec-pr-commenter
on:
  pull_request:
jobs:
  tfsec:
    name: tfsec PR commenter
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
      
      - name: tfsec soft
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          tfsec_args: --force-all-dirs --soft-fail --concise-output
          github_token: ${{ github.token }}
          soft_fail_commenter: true
          
      - name: tfsec fail with critical and high
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          tfsec_args: --force-all-dirs --minimum-severity HIGH --concise-output
          github_token: ${{ github.token }} 
